//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monografia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas_proveedor
    {
        public int idFacturas_proveedor { get; set; }
        public System.DateTime Fecha_alta { get; set; }
        public string Usuario_alta { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string Usuario_baja { get; set; }
        public int Codigo_producto { get; set; }
        public int Id_proveedor { get; set; }
        public int Cantidad_producto { get; set; }
        public decimal Precio_compra { get; set; }
        public int Estado { get; set; }
    
        public virtual proveedor proveedor { get; set; }
    }
}
