//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monografia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista_permisos
    {
        public string ID { get; set; }
        public string TEXTO { get; set; }
        public sbyte SELECCIONADO { get; set; }
        public string GRUPO { get; set; }
        public sbyte INICIO_GRUPO { get; set; }
    }
}
