//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monografia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectotiendaEntities : DbContext
    {
        public proyectotiendaEntities()
            : base("name=proyectotiendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<creditos> creditos { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<detalle_factura> detalle_factura { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<facturas_proveedor> facturas_proveedor { get; set; }
        public virtual DbSet<lista_permisos> lista_permisos { get; set; }
        public virtual DbSet<opciones> opciones { get; set; }
        public virtual DbSet<pagos> pagos { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<promocion> promocion { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<tipo_ventas> tipo_ventas { get; set; }
        public virtual DbSet<unidad_medida> unidad_medida { get; set; }
        public virtual DbSet<usuarios_perfiles> usuarios_perfiles { get; set; }
        public virtual DbSet<usuarios_tienda> usuarios_tienda { get; set; }
        public virtual DbSet<usuario_detalle> usuario_detalle { get; set; }
        public virtual DbSet<usuario_sesion> usuario_sesion { get; set; }
    }
}
