//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monografia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimientos
    {
        public int idMovimientos { get; set; }
        public System.DateTime Fecha_alta { get; set; }
        public string Usuario_alta { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string Usuario_baja { get; set; }
        public decimal Monto { get; set; }
        public int Tipo_movimiento { get; set; }
        public int Estado { get; set; }
        public int Tipo_pago { get; set; }
        public int Idpago { get; set; }
    
        public virtual tipo_movimento tipo_movimento { get; set; }
        public virtual tipo_pago tipo_pago1 { get; set; }
        public virtual pagos pagos { get; set; }
    }
}
