//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monografia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class opciones
    {
        public string ID_OP { get; set; }
        public string NOMBRE_OP { get; set; }
        public string DESCRIPCION_OP { get; set; }
        public Nullable<bool> SELECCIONADO_OP { get; set; }
        public string DETALLE_EXT1 { get; set; }
        public string DETALLE_EXT2 { get; set; }
        public string DETALLE_EXT3 { get; set; }
    }
}
