
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Monografia.Models
{

using System;
    using System.Collections.Generic;
    
public partial class permisos_perfil
{

    public string Id_permiso { get; set; }

    public int Id_perfil { get; set; }



    public virtual lista_permisos lista_permisos { get; set; }

}

}
