//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monografia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.detalle_factura = new HashSet<detalle_factura>();
            this.promocion = new HashSet<promocion>();
            this.historial_inventario = new HashSet<historial_inventario>();
        }
    
        public int Idproducto { get; set; }
        public System.DateTime Fecha_alta { get; set; }
        public string Usuario_alta { get; set; }
        public Nullable<System.DateTime> Fecha_baja { get; set; }
        public string Usuario_baja { get; set; }
        public int Codigo_producto { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
        public int Id_tipoventas { get; set; }
        public decimal Precio_costo { get; set; }
        public decimal Precio_venta { get; set; }
        public decimal Precio_mayoreo { get; set; }
        public int Iddepartamento { get; set; }
        public int Usa_inventario { get; set; }
        public Nullable<int> Cantidad_actual { get; set; }
        public Nullable<int> Cantidad_minima { get; set; }
        public int Idproveedor { get; set; }
    
        public virtual departamento departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocion> promocion { get; set; }
        public virtual tipo_ventas tipo_ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_inventario> historial_inventario { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
